name: mineclaim
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.15.3
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  smooth_page_indicator: ^1.1.0
  grouped_list: ^5.1.2
  easy_date_timeline: ^1.0.2
  google_maps_flutter: ^2.5.0
  carousel_slider: ^4.2.1
  firebase_auth: ^4.16.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  persistent_bottom_nav_bar: ^5.0.2
  geocoding: ^2.1.1
  firebase_storage: ^11.6.4
  flutter_speed_dial: ^7.0.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/app_icons/
  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/Manrope.ttf
          weight: 400
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
    - family: Readex Pro
      fonts: 
        - asset: assets/fonts/ReadexProRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
