// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXFn6QdeHs_X7CIbB832GkHp7a3vcOozs',
    appId: '1:378520027757:android:4ece945ec5362fa68a7564',
    messagingSenderId: '378520027757',
    projectId: 'intellixbot-jqcj',
    storageBucket: 'intellixbot-jqcj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClo4POuqvYz7ErhH6sir0a98131qT53Vs',
    appId: '1:378520027757:ios:757fcb3148bc5be88a7564',
    messagingSenderId: '378520027757',
    projectId: 'intellixbot-jqcj',
    storageBucket: 'intellixbot-jqcj.appspot.com',
    androidClientId: '378520027757-puijge4rf8asa3lru8a9m4a00llt1nv3.apps.googleusercontent.com',
    iosClientId: '378520027757-nqq213opkuktrensknbfaai76jjcpgee.apps.googleusercontent.com',
    iosBundleId: 'com.mineclaim.app',
  );
}
