import 'package:flutter/material.dart';import 'package:mineclaim/core/app_export.dart';import 'package:mineclaim/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:mineclaim/widgets/app_bar/appbar_subtitle_two.dart';import 'package:mineclaim/widgets/app_bar/custom_app_bar.dart';import 'package:mineclaim/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class FaqsGetHelpScreen extends StatelessWidget {FaqsGetHelpScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomSearchView(controller: searchController, hintText: "Search questions...", contentPadding: EdgeInsets.only(top: 17.v, right: 30.h, bottom: 17.v), borderDecoration: SearchViewStyleHelper.outlineGrayTL10, filled: false), SizedBox(height: 26.v), Text("Frequently Asked", style: CustomTextStyles.titleMediumBold_1), SizedBox(height: 22.v), _buildWhoCanBuyAHome(context, text: "How does Relax work?", image: ImageConstant.imgArrowUp), SizedBox(height: 13.v), SizedBox(width: 325.h, child: Text("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Laoreet nulla lorem eget praesent arcu. Nam tellus faucibus blandit dis est ultrices pretium.\nDui faucibus malesuada viverra suspendisse at dictumst aenean eget dolor. Orci ornare morbi ut nibh ultricies at lobortis.", maxLines: 6, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallPrimaryContainer.copyWith(height: 1.50))), SizedBox(height: 18.v), Divider(), SizedBox(height: 19.v), _buildQuestions(context), SizedBox(height: 23.v), Row(children: [Text("Show all", style: CustomTextStyles.titleSmallPrimaryBold), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h, bottom: 2.v))]), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "FAQs"), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildQuestions(BuildContext context) { return Column(children: [_buildWhoCanBuyAHome(context, text: "Who can buy a home?", image: ImageConstant.imgArrowDownBlueGray50020x20), SizedBox(height: 18.v), Divider(), SizedBox(height: 19.v), _buildWhoCanBuyAHome(context, text: "How can I sell my home?", image: ImageConstant.imgArrowDownBlueGray50020x20), SizedBox(height: 18.v), Divider(), SizedBox(height: 19.v), _buildWhoCanBuyAHome(context, text: "How do I contact a local agent?", image: ImageConstant.imgArrowDownBlueGray50020x20)]); } 
/// Common widget
Widget _buildWhoCanBuyAHome(BuildContext context, {required String text, required String image, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text(text, style: CustomTextStyles.titleSmallBold.copyWith(color: theme.colorScheme.primaryContainer))), CustomImageView(imagePath: image, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 2.v))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
